# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb37f3ed8c99074ff8f37ae83b74ab6db2f1664460745b8e943273a4843e5ba28e6627952cb173bff8a2458ec3f956e7021b314009e78fe895c3db1774a7217d

test:
  secret_key_base: ffb87a6edb5ee0cc3401029e4c5251896e798b591abd33a50a396e88bca2290a153ed030a3b387ff07411be8cb21dee5f9b995b48709dc2454cd002695494041

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
